// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zagtrppgmbmguajctyzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZ3RycHBnbWJtZ3VhamN0eXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDYyNTIsImV4cCI6MjA3MDI4MjI1Mn0.vOeRITUuTMVzj3UjjDJf4gIBI2mrBRnjfSYi9Vti8ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});